### ISSUE TITLE
Release script error: "cannot lock ref ..: reference already exists"

### ISSUE THREAD

**Issue by nrenner** [nrenner/brouter-web#190]
Now gulp release failed for the second time since #187, will try without hook next time.

```
yarn build release --tag patch --token xxx
yarn run v1.15.2
$ gulp release --tag patch --token xxx
[19:44:18] Using gulpfile ~/Entwicklung/github/brouter-web/gulpfile.js
[19:44:18] Starting 'release:init'...
[19:44:18] Finished 'release:init' after 6.83 ms
[19:44:18] Starting 'bump:json'...
[19:44:18] Bump to 0.10.1
[19:44:18] Starting 'bump:html'...
[19:44:18] Starting 'clean'...
[19:44:18] Starting 'layers_config'...
[19:44:18] Starting 'scripts'...
[19:44:18] Running in Release mode
[19:44:18] Starting 'styles'...
[19:44:18] Bumped 0.10.0 to 0.10.1 with type: patch
[19:44:18] Finished 'clean' after 76 ms
[19:44:18] Starting 'scripts_config'...
[19:44:18] Starting 'images'...
[19:44:18] Starting 'fonts'...
[19:44:18] Starting 'locales'...
[19:44:18] Finished 'bump:json' after 101 ms
[19:44:18] Finished 'bump:html' after 102 ms
[19:44:18] Starting 'bump'...
[19:44:18] Finished 'bump' after 51 μs
[19:44:18] Starting 'release:commit'...
[19:44:18] Finished 'scripts_config' after 83 ms
[19:44:18] Finished 'layers_config' after 163 ms
[19:44:18] Starting 'layers'...
[19:44:20] Finished 'locales' after 1.6 s
[19:44:21] [master 1bcc2ea] release: 0.10.1
 2 files changed, 2 insertions(+), 2 deletions(-)
 husky > pre-commit (node v10.15.3)
🔍  Finding changed files since git revision 60b9a45.
🎯  Found 2 changed files.
✅  Everything is awesome!

[19:44:21] Finished 'release:commit' after 2.56 s
[19:44:21] Starting 'release:tag'...
[19:44:21] Finished 'release:tag' after 9.59 ms
[19:44:21] Starting 'release:push'...
[19:44:21] Finished 'release:push' after 7.72 ms
[19:44:21]  
[19:44:21] Finished 'styles' after 2.67 s
[19:44:21] Finished 'fonts' after 2.65 s
[19:44:21] Finished 'images' after 2.66 s
[19:44:21] Finished 'layers' after 2.58 s
[19:44:32] Finished 'scripts' after 14 s
[19:44:32] Starting 'default'...
[19:44:32] Finished 'default' after 4.04 μs
[19:44:32] Starting 'release:zip'...
[19:44:32] Build brouter-web.0.10.1.zip
[19:44:33] Finished 'release:zip' after 578 ms
[19:44:33] Starting 'release:publish'...
[19:44:33] Finished 'release:publish' after 1.54 ms
[19:44:33] Starting 'release'...
[19:44:33] Finished 'release' after 3.71 μs
[19:44:34] Release created successfully at https://github.com/nrenner/brouter-web/releases/tag/0.10.1
[19:44:34] Uploading asset brouter-web.0.10.1.zip
/home/norbert/Entwicklung/github/brouter-web/gulpfile.js:297
        if (err) throw err;
                 ^

Error: Command failed: git push origin master --tags
To https://github.com/nrenner/brouter-web.git
 ! [remote rejected] master -> master (failed)
 ! [remote rejected] 0.10.1 -> 0.10.1 (cannot lock ref 'refs/tags/0.10.1': reference already exists)
error: Fehler beim Versenden einiger Referenzen nach 'https://github.com/nrenner/brouter-web.git'

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nrenner** [comment]
Seems fixed now (with pre-push hook removed)
