### ISSUE TITLE
VoiceHints.js:73 Uncaught TypeError when doing an export 

### ISSUE THREAD

**Issue by mschaeuble** [nrenner/brouter-web#751]
When trying to do an export of a route with turnInstructionMode set to "gpsies-style", I get the follow JS exception for some tracks in the console:
```
VoiceHints.js:73 Uncaught TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at e.value (VoiceHints.js:73:34)
    at VoiceHints.js:76:17
    at e.value (VoiceHints.js:39:18)
    at e.value (VoiceHints.js:76:71)
    at e.<anonymous> (VoiceHints.js:75:28)
    at t.exports (togpx.js:86:46)
    at Object.format (Gpx.js:30:24)
    at i._formatTrack (Export.js:131:37)
    at i._export (Export.js:90:33)
```

**Comment by nrenner** [comment]
@mschaeuble As a workaround for now, the fallback server-side download should work (small middle button in export dialog).
